apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: quay.io/keycloak/keycloak:13.0.1
        name: keycloak
        volumeMounts:
        - name: keycloak-config
          mountPath: /tmp/config
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: password } }
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "P6ssw0rd"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_IMPORT
          value: "/tmp/config/break-booking-realm-export.json"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
      volumes:
      - name: keycloak-config
        configMap:
          name: keycloak-config
      restartPolicy: Always

